### ISSUE TITLE
多机部署遇到一个很奇怪的问题

### ISSUE THREAD

**Issue by ChinaArJun** [VoneChain-CS/fabric-gm#6]
单机部署暂时没发现问题，多机部署的时候遇到orderer节点无法连接导致no Raft leader

我在docker-compose.yaml host域名指向都是为本地地址，但orderer日志显示：
2021-10-26 02:35:12.400 UTC [orderer.consensus.etcdraft] logSendFailure -> DEBU 164d Failed to send StepRequest to 1, because: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 106.****:7050: i/o timeout" channel=byfn-sys-channel node=2
2021-10-26 02:25:44.486 UTC [grpc] Warningf -> DEBU 6a3 grpc: addrConn.createTransport failed to connect to {orderer.***.com:7050  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 106.****:7050: i/o timeout". Reconnecting...

以上日志信息显示连接了外网地址？十分不解，我官方原版部署不会有这个问题，而且hosts解析都设置指向本地的，求指导一下感谢

**Comment by newsmys** [comment]
> 单机部署暂时没发现问题，多机部署的时候遇到orderer节点无法连接导致no Raft leader
> 
> 我在docker-compose.yaml host域名指向都是为本地地址，但orderer日志显示： 2021-10-26 02:35:12.400 UTC [orderer.consensus.etcdraft] logSendFailure -> DEBU 164d Failed to send StepRequest to 1, because: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 106.__**:7050: i/o timeout" channel=byfn-sys-channel node=2 2021-10-26 02:25:44.486 UTC [grpc] Warningf -> DEBU 6a3 grpc: addrConn.createTransport failed to connect to {orderer.**_.com:7050 0 }. Err: connection error: desc = "transport: Error while dialing dial tcp 106._***:7050: i/o timeout". Reconnecting...
> 
> 以上日志信息显示连接了外网地址？十分不解，我官方原版部署不会有这个问题，而且hosts解析都设置指向本地的，求指导一下感谢

如果是集群下的多机部署，则需要保证所有的节点在同一个network，基于docker-compose的方式是没有问题的，只需确保机器之间的通信是顺畅的

**Comment by ChinaArJun** [comment]
> > 单机部署暂时没发现问题，多机部署的时候遇到orderer节点无法连接导致no Raft leader
> > 我在 2021-10-26 02:35:12.400 UTC [orderer.consensus.etcdraft] logSendFailure -> DEBU 164d Failed to send StepRequest to 1 ，因为：rpc 错误：代码 = 不可用 desc = 连接错误：desc = “传输：拨号时出错 tcp 106.__ **:7050：i/o 超时” channel=byfn-sys-channel node=2 2021-10-26 02:25:44.486 UTC [grpc] Warningf -> DEBU 6a3 grpc：addrConn.createTransport 无法连接到 {orderer. **_.com:7050 0 }。Err: 连接错误: desc = "传输: 拨号拨号 tcp 106 时出错。_ ***:7050: i/o 超时"。正在重新连接...
> > 以上日志信息显示连接了外网地址？十分不解，我官方原版部署不会有这个问题，而且hosts解析都设置指向本地的，求指导一下感谢
> 
> 如果是集群下的多机部署，则需要保证所有的节点在同一个network，基于docker-compose的方式是没有问题的，只需确保机器之间的通信是顺畅的

多谢，昨天测试也是发现在同一个docker network下是可以连接，后面用docker swarm网络解决了这个问题
